<?php
/**
 * Headless allows you to use Backdrop CMS as an API.
 */
function headless_menu() {
  $items = array();
  // Return JSON for individual nodes.
  $items['api/node/%/%'] = array(
    'page callback' => 'headless_type',
    'access callback' => TRUE,
    'page arguments' => array(2, 3),
  );
  // Return JSON for individual terms.
  $items['api/%/term/%'] = array(
    'page callback' => 'headless_term_item',
    'access callback' => TRUE,
    'page arguments' => array(1, 3),
  );
  $items['api/views/%'] = array(
    'page callback' => 'headless_views',
    'access callback' => TRUE,
    'page arguments' => array(2),
  );
  if (module_exists('paragraphs')) {
    // Return json for individual paragraphs.
    $items['api/paragraphs/%/%'] = array(
      'page callback' => 'headless_paragraphs_item',
      'access callback' => TRUE,
      'page arguments' => array(2, 3),
    );
  }
  $items['admin/config/services/headless'] = array(
    'title' => 'Headless settings',
    'description' => 'Configure the entity types you wish to expose as json endpoints.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('headless_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/headless.admin.inc',
  );

  // Router: allow API queries via string paths.
  $items['api/router/%'] = array(
    'title' => 'Headless router',
    'description' => 'Allow queries via string like /api/my-node-title',
    'page callback' => 'headless_router',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'includes/headless.router.inc',
  );

  return $items;
}

/**
 * Page callback for node types.
 */
function headless_type($type, $nid) {
  $config = config_get('headless.settings', 'node');
  if ($config[$type] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }
  $my_json = node_load($nid);
  backdrop_json_output($my_json);
  backdrop_exit();
}

/**
 * Page callback for terms.
 */
function headless_term_item($vocab, $tid) {
  $config = config_get('headless.settings', 'vocabularies');
  if ($config[$vocab] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }
  $my_json = taxonomy_term_load($tid);
  backdrop_json_output($my_json);
  backdrop_exit();
}

/**
 * Page callback for views.
 */
function headless_views($view) {
  $config = config_get('headless.settings', 'views');
  if ($config[$view] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }
  $results = views_get_view_result($view);
  $count = count($results);
  $my_json = [
    'results' => $results,
    'count' => $count,
  ];
  backdrop_json_output($my_json);
  backdrop_exit();
}
/**
 * Page callback for paragraph types.
 */
function headless_paragraphs_item($type, $entity_id) {
  $config = config_get('headless.settings', 'paragraphs');
  if ($config[$type] != 1) {
    $json_error = ['code' => 404];
    backdrop_json_output($json_error);
    backdrop_exit();
  }
  $result = paragraphs_item_load($entity_id);
  backdrop_json_output($result);
  backdrop_exit();
}
